application: ravishakya77
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /blog/.*
  script: newpost.app
- url: /blog
  script: newpost.app
- url: /blog.json
  script: newpost.app

